global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'stream-relay-monitor'

scrape_configs:
  - job_name: 'relay'
    static_configs:
      - targets: ['192.168.1.3:8080']
        labels:
          service: 'stream-relay-go'
    metrics_path: '/metrics'
    scrape_interval: 5s
